//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosClase2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JATOrdenDetalle
    {
        public int CodigoOrdenDetalle { get; set; }
        public int CodigoProducto { get; set; }
        public int CodigoOrden { get; set; }
        public int CantidadProducto { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual JATOrden JATOrden { get; set; }
        public virtual JATProducto JATProducto { get; set; }
    }
}
