//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosClase2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACJob
    {
        public int IdJob { get; set; }
        public string Type { get; set; }
        public string Company { get; set; }
        public string Logo { get; set; }
        public string Url { get; set; }
        public string Position { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string How_to_apply { get; set; }
        public string Token { get; set; }
        public string Is_public { get; set; }
        public string Is_validated { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> Expires_at { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public int IdCategoria { get; set; }
        public string Usuario_Inserto { get; set; }
        public Nullable<System.DateTime> Fecha_Inserto { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual ACCategory ACCategory { get; set; }
    }
}
