//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosClase2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOTDetail
    {
        public int DetailId { get; set; }
        public int MasterId { get; set; }
        public string DetailValue { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual DOTMaster DOTMaster { get; set; }
    }
}
