//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosClase2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class JLPCTPay
    {
        public int receiptNumber { get; set; }
        public int studentNumber { get; set; }
        public System.DateTime paymentDate { get; set; }
        public decimal amount { get; set; }
    
        public virtual JLPCTStudentMaster JLPCTStudentMaster { get; set; }
    }
}
