//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosClase2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class JLPCTStudentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JLPCTStudentMaster()
        {
            this.JLPCTPay = new HashSet<JLPCTPay>();
        }
    
        public int studentNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int programmeCode { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<int> phoneNo { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<int> notes { get; set; }
        public string fYCF { get; set; }
        public bool deleted { get; set; }
        public string usuarioCreo { get; set; }
        public System.DateTime fechaCreo { get; set; }
        public string usuarioModifico { get; set; }
        public string fechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JLPCTPay> JLPCTPay { get; set; }
    }
}
