//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCurso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BBDDLocalClase4Entities : DbContext
    {
        public BBDDLocalClase4Entities()
            : base("name=BBDDLocalClase4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Depto> Depto { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EmpleadoDireccion> EmpleadoDireccion { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
    
        [DbFunction("BBDDLocalClase4Entities", "FEmpleadoDepartamento")]
        public virtual IQueryable<FEmpleadoDepartamento_Result> FEmpleadoDepartamento(Nullable<int> codigoEmpleado)
        {
            var codigoEmpleadoParameter = codigoEmpleado.HasValue ?
                new ObjectParameter("CodigoEmpleado", codigoEmpleado) :
                new ObjectParameter("CodigoEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FEmpleadoDepartamento_Result>("[BBDDLocalClase4Entities].[FEmpleadoDepartamento](@CodigoEmpleado)", codigoEmpleadoParameter);
        }
    
        public virtual ObjectResult<PPaisDeptoMunicipioListar_Result> PPaisDeptoMunicipioListar(Nullable<int> codigoPais)
        {
            var codigoPaisParameter = codigoPais.HasValue ?
                new ObjectParameter("CodigoPais", codigoPais) :
                new ObjectParameter("CodigoPais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PPaisDeptoMunicipioListar_Result>("PPaisDeptoMunicipioListar", codigoPaisParameter);
        }
    }
}
